# Generated by Django 4.2 on 2024-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='comic_images/')),
            ],
        ),
    ]
