# Generated by Django 4.2 on 2024-12-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0002_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
