# Generated by Django 4.2 on 2024-12-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
